### ISSUE TITLE
GKE : trace work with post-forward but not if calling by https url

### ISSUE THREAD

**Issue by raphaelauv** [GoogleCloudPlatform/opentelemetry-operations-python#188]
I have a pod using `CloudTraceSpanExporter` inside a GKE auto-pilot with CLOUD NAT (private cluster)

If I call the api by the https://xxxxxx.com it do not produce a trace ( the api work and answer http request on the url without any problem )

but if I post-forward the pod on my host it produce a trace in `gcp trace`

I have activate the DEBUG logging but it do not produce any error when calling by the https URL

```python
loggers = [logging.getLogger(name) for name in logging.root.manager.loggerDict]
for logger in loggers:
    logger.setLevel(logging.DEBUG)
```

the LB conf 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-XXXX-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
    ingress.gcp.kubernetes.io/pre-shared-cert: {{ .Values.val.cert }}
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: XXXXX-np-service
                port:
                  number: 60000

```
